### ISSUE TITLE
Make the test output language validation less strict.

### ISSUE THREAD

**Issue by tjheslin1** [theangrydev/yatspec-fluent#1]
Example:

```java
given(theInventory.willReturn().aDirectoryNumber(DIR_NUM));
when(theClientRequestsADirectoryNumbersDetails());
then(theResponse).hasCode(200);
and(theResponse).containsDetails(DIR_DETAILS);
```

In the event that my then's have to be in a specific order and my first assertion doesn't use the `then()` framework (e.g a wiremock `verify`), the framework then complains that I have not provided a `then()` before my `and()`'s.

**Comment by theangrydev** [comment]
Done! I removed that validation in version 1.6.0
